# Generated by Django 2.0.4 on 2018-04-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('surname', models.CharField(max_length=120, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
